[package]
name = "kopium"
description = "kubernetes openapi unmangler"
version = "0.4.0"
edition = "2021"
authors = [
    "clux <sszynrae@gmail.com>",
]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/kube-rs/kopium"
keywords = ["kubernetes", "openapi"]
categories = ["command-line-utilities"]

[[bin]]
doc = false
name = "kopium"
path = "src/main.rs"

[lib]
name = "kopium"
path = "src/lib.rs"

[dependencies]
kube = { version = "0.64.0", features = ["derive"] }
k8s-openapi = { version = "0.13.1", features = ["v1_22"] }
tokio = { version = "1.14.0", features = ["full"] }
anyhow = "1.0.48"
log = "0.4.14"
env_logger = "0.9.0"
serde_json = "1.0.72"
quote = "1.0.10"
serde = { version = "1.0.130", features = ["derive"] }
structopt = "0.3"
