[package]
name = "kopium"
description = "kubernetes openapi unmangler"
version = "0.12.0"
edition = "2021"
authors = [
    "clux <sszynrae@gmail.com>",
]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/kube-rs/kopium"
keywords = ["kubernetes", "openapi"]
categories = ["command-line-utilities"]

[[bin]]
doc = false
name = "kopium"
path = "src/main.rs"

[lib]
name = "kopium"
path = "src/lib.rs"

[dependencies]
k8s-openapi = { version = "0.15.0", features = ["v1_23"] }
tokio = { version = "1.14.0", features = ["full"] }
anyhow = "1.0.59"
log = "0.4.17"
env_logger = "0.9.0"
serde_json = "1.0.82"
clap = { version = "4.0", features = ["cargo", "derive"] }
clap_complete = "4.0"
quote = "1.0.10"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.23"
heck = "0.4.0"

[dependencies.kube]
version = "0.74.0"
#git = "https://github.com/kube-rs/kube-rs.git"
#branch = "master"
features = ["derive"]

[dev-dependencies]
schemars = "0.8.10"
typed-builder = "0.10.0"
